#TODO translate to xml.

parameters:
    zicht_framework_extra.embed_helper.class: Zicht\Bundle\FrameworkExtraBundle\Helper\EmbedHelper
services:
    zicht_embed_helper:
        class: %zicht_framework_extra.embed_helper.class%
        arguments:
            - @service_container
    zicht_twig_extension:
        class: Zicht\Bundle\FrameworkExtraBundle\Twig\Extension
        tags:
            - { name: twig.extension }
        arguments:
            - @zicht_embed_helper
            - @zicht_annotation_registry
            - @translator
            - @security_context

    zicht_annotation_registry:
        class: Zicht\Bundle\FrameworkExtraBundle\Helper\AnnotationRegistry

    zicht_framework_extra.form.zicht_parent_choice_type:
        class: Zicht\Bundle\FrameworkExtraBundle\Form\ParentChoiceType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: zicht_parent_choice }
