services:
    zicht_embed_helper:
        class: Zicht\Bundle\FrameworkExtraBundle\Helper\EmbedHelper
        arguments:
            - @service_container
    zicht_twig_extension:
        class: Zicht\Bundle\FrameworkExtraBundle\Twig\Extension
        tags:
            - { name: twig.extension }
        arguments:
            - @zicht_embed_helper